package indecisivegainz.view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.layout.BorderPane;

public class CreateWorkoutPane {
	@FXML
	private BorderPane createWorkoutPane;
	@FXML
	private TextField workoutNameTF;
	@FXML
	private ComboBox muscleGroupCB;
	@FXML
	private Button createWorkoutButton;
	@FXML
	private Button clearButton;

	// Event Listener on Button[#createWorkoutButton].onAction
	@FXML
	public void createNewWorkout(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#clearButton].onAction
	@FXML
	public void clearFields(ActionEvent event) {
		// TODO Autogenerated
	}
}
