package indecisivegainz.view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

public class GenerateRoutinePane 
{
	@FXML
	private Button generateRoutineButton;
	@FXML
	private Button clearButton;
	@FXML
	private ComboBox muscleGroupCB1;
	@FXML
	private ComboBox muscleGroupCB2;
	@FXML
	private TextField numWorkoutsTF1;
	@FXML
	private ComboBox muscleGroupCB3;
	@FXML
	private ComboBox muscleGroupCB4;
	@FXML
	private TextField numWorkoutsTF2;
	@FXML
	private TextField numWorkoutsTF3;
	@FXML
	private TextField numWorkoutsTF4;

	// Event Listener on Button[#generateRoutineButton].onAction
	@FXML
	public void generateRoutineButton(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#clearButton].onAction
	@FXML
	public void clearFields(ActionEvent event) {
		// TODO Autogenerated
	}
}
