package indecisivegainz.view;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.layout.BorderPane;

public class MainMenuBar
{
	@FXML
	private BorderPane menu;
	@FXML
	private Button logoutButton;
	@FXML
	private Button createWorkoutButton;
	@FXML
	private Button generateRoutineButton;

	// Event Listener on Button[#logoutButton].onAction
	@FXML
	public void logout() {
		// TODO Autogenerated
	}
	// Event Listener on Button[#createWorkoutButton].onAction
	@FXML
	public void loadCreateWorkoutPane() 
	{
		ViewNavigator.loadPane("CreateWorkoutPane.fxml");
	}
	// Event Listener on Button[#trackWorkoutButton].onAction
	@FXML
	public void loadMuscleGroupsPane() 
	{
		ViewNavigator.loadPane("MuscleGroupsPane.fxml");
	}
	// Event Listener on Button[#generateRoutineButton].onAction
	@FXML
	public void loadGenerateRoutineOptions() 
	{
		ViewNavigator.loadPane("GenerateRoutinePane.fxml");
	}
}
