package indecisivegainz.view;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.layout.BorderPane;

public class MainMenuBar {
	@FXML
	private BorderPane menu;
	@FXML
	private Button logoutButton;
	@FXML
	private Button createWorkoutButton;
	@FXML
	private Button trackWorkoutButton;
	@FXML
	private Button viewWorkoutsButton;
	@FXML
	private Button generateRoutineButton;

	// Event Listener on Button[#logoutButton].onAction
	@FXML
	public void logout(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#createWorkoutButton].onAction
	@FXML
	public void loadCreateWorkoutPane(ActionEvent event) 
	{
		ViewNavigator.loadPane("CreateWorkoutPane.fxml");
	}
	// Event Listener on Button[#trackWorkoutButton].onAction
	@FXML
	public void loadTrackWorkoutPane(ActionEvent event) 
	{
		ViewNavigator.loadPane("TrackWorkoutPane.fxml");
	}
	// Event Listener on Button[#viewWorkoutsButton].onAction
	@FXML
	public void loadViewWorkoutsPane(ActionEvent event) 
	{
		ViewNavigator.loadPane("WorkoutsPane.fxml");
	}
	// Event Listener on Button[#generateRoutineButton].onAction
	@FXML
	public void loadGenerateRoutineOptions(ActionEvent event) 
	{
		ViewNavigator.loadPane("GenerateRoutinePane.fxml");
	}
}
